# Generated by Django 3.2.5 on 2023-03-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230327_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink_name',
            new_name='drink',
        ),
    ]
